# Generated by Django 5.2.15 on 2026-07-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0005_agency_about_agency_address_agency_business_hours_and_more'),
        ('leads', '0004_lead_leads_lead_agency__1bafd0_idx_and_more'),
        ('social_media', '0005_socialaccount_webhook_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='meta', max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(default='received', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('external_user_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('profile_image_url', models.URLField(blank=True, max_length=1000)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_contacts', to='agencies.agency')),
                ('linked_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_contacts', to='leads.lead')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='social_media.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('external_conversation_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed'), ('spam', 'Spam')], default='open', max_length=20)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_conversations', to='agencies.agency')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inbox_conversations', to=settings.AUTH_USER_MODEL)),
                ('linked_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_conversations', to='leads.lead')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='social_media.socialaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='crm_inbox.socialcontact')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('sticker', 'Sticker'), ('postback', 'Postback'), ('unsupported', 'Unsupported')], default='text', max_length=20)),
                ('sender_external_id', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm_inbox.conversation')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_media.socialaccount')),
            ],
            options={
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='socialcontact',
            index=models.Index(fields=['agency', 'platform', 'last_seen_at'], name='crm_inbox_s_agency__f3d563_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialcontact',
            constraint=models.UniqueConstraint(fields=('social_account', 'external_user_id'), name='unique_social_contact_per_account'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agency', 'status', 'last_message_at'], name='crm_inbox_c_agency__c8459a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agency', 'assigned_agent', 'status'], name='crm_inbox_c_agency__aaa1ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('social_account', 'external_conversation_id'), name='unique_external_conversation_per_account'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='crm_inbox_s_convers_9722d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialmessage',
            constraint=models.UniqueConstraint(fields=('social_account', 'provider_message_id'), name='unique_provider_message_per_account'),
        ),
    ]
