# Generated by Django 5.2.15 on 2026-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0002_alter_sitevisit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='scheduled_email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='scheduled_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
