# Generated by Django 5.2.15 on 2026-07-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0003_sitevisit_scheduled_email_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='reminder_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
