# Generated by Django 5.2.15 on 2026-07-11 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_about_agency_address_agency_business_hours_and_more'),
        ('leads', '0004_lead_leads_lead_agency__1bafd0_idx_and_more'),
        ('properties', '0007_property_properties__agency__6ac544_idx_and_more'),
        ('site_visits', '0004_sitevisit_cancellation_reason_sitevisit_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['agency', 'status', 'scheduled_at'], name='site_visits_agency__3ae314_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['agency', 'assigned_agent', 'scheduled_at'], name='site_visits_agency__aa2d30_idx'),
        ),
    ]
