# Generated by Django 5.2.15 on 2026-06-19 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_remove_agency_slug_remove_agency_updated_at_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyuser',
            old_name='agency_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='agencyuser',
            name='agency_license_number',
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='role',
            field=models.CharField(default='agency_owner', max_length=50),
        ),
    ]
