# Generated by Django 5.2.15 on 2026-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_agency_name_agencyuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('agency_owner', 'Agency Owner'), ('agency_manager', 'Agency Manager'), ('agent', 'Agent')], default='agency_owner', max_length=50),
        ),
    ]
