# Generated by Django 5.2.15 on 2026-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_agencyuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
