# Generated by Django 5.2.15 on 2026-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agent_profiles/'),
        ),
    ]
