# Generated by Django 5.2.15 on 2026-07-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agencyuser_bio_agencyuser_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyuser',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
