# Generated by Django 5.2.15 on 2026-07-11 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_about_agency_address_agency_business_hours_and_more'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_completed', 'Site Visit Completed'), ('negotiating', 'Negotiating'), ('token_booking', 'Token / Booking'), ('won', 'Won'), ('lost', 'Lost'), ('follow_up_later', 'Follow Up Later'), ('archived', 'Archived')], default='new', max_length=40),
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_completed', 'Site Visit Completed'), ('negotiating', 'Negotiating'), ('token_booking', 'Token / Booking'), ('won', 'Won'), ('lost', 'Lost'), ('follow_up_later', 'Follow Up Later'), ('archived', 'Archived')], max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_status_history', to='agencies.agency')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
