# Generated by Django 5.2.15 on 2026-07-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_created_by_lead_follow_up_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_reminder_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
