# Generated by Django 5.2.15 on 2026-07-11 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_about_agency_address_agency_business_hours_and_more'),
        ('leads', '0003_lead_follow_up_reminder_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agency', 'status', 'created_at'], name='leads_lead_agency__1bafd0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agency', 'assigned_agent', 'status'], name='leads_lead_agency__c015c8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agency', 'follow_up_status', 'next_follow_up_at'], name='leads_lead_agency__6f99a3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agency', 'phone'], name='leads_lead_agency__197270_idx'),
        ),
    ]
