# Generated by Django 5.2.16 on 2026-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_leads_lead_agency__1bafd0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
