# Generated by Django 5.2.16 on 2026-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_lead_custom_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadinteraction",
            name="direction",
            field=models.CharField(
                choices=[
                    ("inbound", "Inbound"),
                    ("outbound", "Outbound"),
                    ("internal", "Internal Note"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("whatsapp", "WhatsApp"),
                    ("viber", "Viber"),
                    ("phone", "Phone Inquiry"),
                    ("manual", "Manual"),
                    ("referral", "Referral"),
                    ("walk_in", "Walk In"),
                    ("property_portal", "Property Portal"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="leadinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("whatsapp", "WhatsApp"),
                    ("viber", "Viber"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("meeting", "Meeting"),
                    ("walk_in", "Walk In"),
                    ("property_portal", "Property Portal"),
                    ("site_visit", "Site Visit"),
                    ("note", "Note"),
                    ("other", "Other"),
                ],
                default="note",
                max_length=30,
            ),
        ),
    ]
