# Generated by Django 5.2.16 on 2026-08-07 07:13

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def initialize_existing_assignments(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    now = timezone.now()
    Lead.objects.filter(
        assigned_agent__isnull=False,
        assigned_at__isnull=True,
        status__in=[
            "new", "contacted", "interested", "site_visit_scheduled",
            "site_visit_completed", "negotiating", "token_booking",
            "follow_up_later",
        ],
    ).update(
        assigned_at=now,
        last_agent_activity_at=now,
        response_due_at=now + timedelta(minutes=30),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_agency_is_website_published_agency_website_config_and_more"),
        ("leads", "0006_leadinteraction_direction_alter_lead_source_and_more"),
        ("properties", "0013_backfill_listing_freshness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadAssignmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("match_location", models.CharField(blank=True, max_length=255)),
                (
                    "match_property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("house", "House"),
                            ("land", "Land"),
                            ("apartment", "Apartment"),
                            ("flat", "Flat"),
                            ("commercial", "Commercial"),
                            ("office_space", "Office Space"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "assignment_method",
                    models.CharField(
                        choices=[
                            ("specific_agent", "Specific Agent"),
                            ("listing_agent", "Listing Agent"),
                            ("round_robin", "Round Robin"),
                        ],
                        default="round_robin",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeadAutomationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("response", "First Response"),
                            ("duplicate", "Duplicate Flagged"),
                            ("escalated", "Escalated"),
                            ("neglect_alert", "Neglect Alert"),
                            ("reassigned", "Reassigned"),
                            ("follow_up_reminder", "Follow-up Reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadAutomationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "fallback_assignment",
                    models.CharField(
                        choices=[
                            ("listing_agent", "Listing Agent"),
                            ("round_robin", "Round Robin"),
                            ("unassigned", "Leave Unassigned"),
                        ],
                        default="listing_agent",
                        max_length=30,
                    ),
                ),
                ("max_active_leads_per_agent", models.PositiveIntegerField(default=50)),
                ("response_sla_minutes", models.PositiveIntegerField(default=30)),
                ("escalation_minutes", models.PositiveIntegerField(default=120)),
                ("inactive_reassign_hours", models.PositiveIntegerField(default=48)),
                ("manager_alert_hours", models.PositiveIntegerField(default=24)),
                ("follow_up_reminder_hours", models.PositiveIntegerField(default=24)),
                ("auto_reassign_inactive", models.BooleanField(default=True)),
                ("auto_detect_duplicates", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeadDuplicateFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Needs Review"),
                            ("confirmed", "Confirmed Duplicate"),
                            ("dismissed", "Not a Duplicate"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-score", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="assignment_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="first_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_agent_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="neglect_alerted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="reassigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="reassignment_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="response_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="response_time_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            initialize_existing_assignments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["agency", "response_due_at", "first_responded_at"],
                name="leads_lead_agency__83fddd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["agency", "assigned_agent", "last_agent_activity_at"],
                name="leads_lead_agency__4caf49_idx",
            ),
        ),
        migrations.AddField(
            model_name="leadassignmentrule",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_assignment_rules",
                to="agencies.agency",
            ),
        ),
        migrations.AddField(
            model_name="leadassignmentrule",
            name="assign_to_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_assignment_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadassignmentrule",
            name="match_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_assignment_rules",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="leadautomationevent",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_automation_events",
                to="agencies.agency",
            ),
        ),
        migrations.AddField(
            model_name="leadautomationevent",
            name="from_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_automation_events_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadautomationevent",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_events",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="leadautomationevent",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="leads.leadassignmentrule",
            ),
        ),
        migrations.AddField(
            model_name="leadautomationevent",
            name="to_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_automation_events_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadautomationsettings",
            name="agency",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_automation_settings",
                to="agencies.agency",
            ),
        ),
        migrations.AddField(
            model_name="leadautomationsettings",
            name="round_robin_last_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_round_robin_cursors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadduplicateflag",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_duplicate_flags",
                to="agencies.agency",
            ),
        ),
        migrations.AddField(
            model_name="leadduplicateflag",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_candidates",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="leadduplicateflag",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_flags",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="leadduplicateflag",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_lead_duplicates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leadassignmentrule",
            index=models.Index(
                fields=["agency", "is_active", "priority"],
                name="leads_leada_agency__811e56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadautomationevent",
            index=models.Index(
                fields=["agency", "event_type", "created_at"],
                name="leads_leada_agency__7ff7ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadduplicateflag",
            constraint=models.UniqueConstraint(
                fields=("lead", "candidate"), name="unique_lead_duplicate_pair"
            ),
        ),
    ]
