services:
  db:
    image: postgres:16
    container_name: real_estate_db
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: real_estate_api
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: real_estate_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "True"

      META_APP_ID: "your_meta_app_id"
      META_APP_SECRET: "your_meta_app_secret"
      META_GRAPH_VERSION: "v23.0"
      META_REDIRECT_URI: "https://your-ngrok-url.ngrok-free.app/api/social/connections/meta/callback/"
      FRONTEND_SOCIAL_SUCCESS_URL: "http://localhost:3000/dashboard/social"
    depends_on:
      - db

volumes:
  postgres_data:
