"""
Django settings for realtyos project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)

    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name)

    if value is None:
        return list(default or [])

    return [item.strip() for item in value.split(",") if item.strip()]


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
MAX_UPLOAD_SIZE_MB = int(os.getenv("MAX_UPLOAD_SIZE_MB", "15"))
ALLOWED_MEDIA_CONTENT_TYPES = env_list(
    "ALLOWED_MEDIA_CONTENT_TYPES",
    ["image/jpeg", "image/png", "image/webp", "application/pdf", "video/mp4"],
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is disabled."
        )

    SECRET_KEY = "django-insecure-development-only-change-me"

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["localhost", "127.0.0.1","handled-slimness-unsightly.ngrok-free.dev","161.118.176.119"],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'users',
    'agencies',
    'properties',
    'leads',
    'site_visits',
    'social_media',
    'crm_inbox',
]

CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", True)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
ROOT_URLCONF = 'realtyos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'realtyos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "real_estate_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Nexora RealtyOS <noreply@nexora.com>",
)
# docker compose logs -f api

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.AgencyUser"


META_APP_ID = os.getenv("META_APP_ID")
META_APP_SECRET = os.getenv("META_APP_SECRET")
META_GRAPH_VERSION = os.getenv("META_GRAPH_VERSION", "v23.0")
META_REDIRECT_URI = os.getenv("META_REDIRECT_URI")
META_LOGIN_CONFIG_ID = os.getenv("META_LOGIN_CONFIG_ID")
META_WEBHOOK_VERIFY_TOKEN = os.getenv("META_WEBHOOK_VERIFY_TOKEN", "")
FRONTEND_SOCIAL_SUCCESS_URL = os.getenv(
    "FRONTEND_SOCIAL_SUCCESS_URL",
    "http://localhost:3000/dashboard/social"
)
PUBLIC_API_BASE_URL = os.getenv("PUBLIC_API_BASE_URL", "")
INSTAGRAM_CONTAINER_POLL_ATTEMPTS = int(
    os.getenv("INSTAGRAM_CONTAINER_POLL_ATTEMPTS", "10")
)
INSTAGRAM_CONTAINER_POLL_INTERVAL_SECONDS = float(
    os.getenv("INSTAGRAM_CONTAINER_POLL_INTERVAL_SECONDS", "2")
)
META_HTTP_CONNECT_TIMEOUT_SECONDS = float(
    os.getenv("META_HTTP_CONNECT_TIMEOUT_SECONDS", "10")
)
META_HTTP_READ_TIMEOUT_SECONDS = float(
    os.getenv("META_HTTP_READ_TIMEOUT_SECONDS", "60")
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.AgencyJWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "registration": os.getenv("THROTTLE_REGISTRATION", "5/hour"),
        "login": os.getenv("THROTTLE_LOGIN", "10/minute"),
        "token_refresh": os.getenv("THROTTLE_TOKEN_REFRESH", "30/minute"),
        "otp_verify": os.getenv("THROTTLE_OTP_VERIFY", "10/minute"),
        "otp_resend": os.getenv("THROTTLE_OTP_RESEND", "3/hour"),
        "public_submission": os.getenv("THROTTLE_PUBLIC_SUBMISSION", "10/hour"),
        "public_event": os.getenv("THROTTLE_PUBLIC_EVENT", "120/hour"),
        "oauth": os.getenv("THROTTLE_OAUTH", "20/hour"),
        "social_publish": os.getenv("THROTTLE_SOCIAL_PUBLISH", "30/hour"),
        "meta_webhook": os.getenv("THROTTLE_META_WEBHOOK", "600/minute"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": env_bool("JWT_ROTATE_REFRESH_TOKENS", True),
    "BLACKLIST_AFTER_ROTATION": False,
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
SPECTACULAR_SETTINGS = {
    "TITLE": "Nexora RealtyOS API",
    "DESCRIPTION": "Listings Dekhi Leads Samma, Leads Dekhi Deals Samma",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "AreaUnitEnum": "properties.models.AREA_UNIT_CHOICES",
        "SocialPostPlatformEnum": "social_media.models.SOCIAL_POST_PLATFORM_CHOICES",
        "SocialAccountPlatformEnum": "social_media.models.SOCIAL_ACCOUNT_PLATFORM_CHOICES",
        "ConversationStatusEnum": "crm_inbox.models.Conversation.STATUS_CHOICES",
        "MessageDeliveryStatusEnum": "crm_inbox.models.SocialMessage.STATUS_CHOICES",
    },
}
