# Generated by Django 5.2.15 on 2026-06-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_remove_agency_slug_remove_agency_updated_at_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Reel'), ('brochure', 'Brochure'), ('floor_plan', 'Floor Plan'), ('document', 'Document')], default='image', max_length=50)),
                ('file', models.FileField(upload_to='property_media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_media/thumbnails/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_media', to='agencies.agency')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
        ),
    ]
