# Generated by Django 5.2.15 on 2026-06-21 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='built_up_area_unit',
            field=models.CharField(choices=[('aana', 'Aana'), ('ropani', 'Ropani'), ('kattha', 'Kattha'), ('dhur', 'Dhur'), ('sqft', 'Square Feet'), ('sqm', 'Square Meter')], default='sqft', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='built_up_area_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(default='NPR', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area_unit',
            field=models.CharField(blank=True, choices=[('aana', 'Aana'), ('ropani', 'Ropani'), ('kattha', 'Kattha'), ('dhur', 'Dhur'), ('sqft', 'Square Feet'), ('sqm', 'Square Meter')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access_unit',
            field=models.CharField(choices=[('ft', 'Feet'), ('m', 'Meter')], default='ft', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_property_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment'), ('flat', 'Flat'), ('commercial', 'Commercial'), ('office_space', 'Office Space')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('under_negotiation', 'Under Negotiation'), ('sold', 'Sold'), ('rented', 'Rented'), ('hidden', 'Hidden'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='property_media/'),
        ),
    ]
