# Generated by Django 5.2.15 on 2026-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_amenities_property_built_up_area_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_up_area_unit',
            field=models.CharField(choices=[('aana', 'Aana'), ('ropani', 'Ropani'), ('kattha', 'Kattha'), ('dhur', 'Dhur'), ('bigha', 'Bigha'), ('sqft', 'Square Feet'), ('sqm', 'Square Meter')], default='sqft', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area_unit',
            field=models.CharField(blank=True, choices=[('aana', 'Aana'), ('ropani', 'Ropani'), ('kattha', 'Kattha'), ('dhur', 'Dhur'), ('bigha', 'Bigha'), ('sqft', 'Square Feet'), ('sqm', 'Square Meter')], max_length=20),
        ),
    ]
