# Generated by Django 5.2.15 on 2026-07-11 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_about_agency_address_agency_business_hours_and_more'),
        ('leads', '0002_lead_created_by_lead_follow_up_status_and_more'),
        ('properties', '0005_property_facing_direction_property_furnishing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Property View'), ('whatsapp_click', 'WhatsApp Click'), ('viber_click', 'Viber Click'), ('call_click', 'Call Click'), ('inquiry', 'Inquiry'), ('site_visit_request', 'Site Visit Request')], max_length=40)),
                ('visitor_id', models.CharField(blank=True, max_length=100)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_events', to='agencies.agency')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_events', to='leads.lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'event_type', 'created_at'], name='properties__agency__3e4afb_idx'), models.Index(fields=['property', 'event_type', 'created_at'], name='properties__propert_fdbcb2_idx')],
            },
        ),
    ]
