# Generated by Django 5.2.15 on 2026-07-11 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_about_agency_address_agency_business_hours_and_more'),
        ('properties', '0006_propertyevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agency', 'is_published', 'status'], name='properties__agency__6ac544_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agency', 'property_type', 'purpose'], name='properties__agency__95a0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agency', 'assigned_agent', 'status'], name='properties__agency__ee8e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district'], name='properties__city_bd502c_idx'),
        ),
    ]
