# Generated by Django 5.2.16 on 2026-08-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_property_properties__agency__6ac544_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="seo_description",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="property",
            name="share_slug",
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="property",
            name="video_tour_url",
            field=models.URLField(blank=True),
        ),
    ]
