# Generated by Django 5.2.16 on 2026-08-06 09:31

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_share_slugs(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    seen = set()
    for property_obj in Property.objects.order_by("agency_id", "id").iterator():
        candidate = property_obj.share_slug.strip()
        key = (property_obj.agency_id, candidate)
        if not candidate or key in seen:
            stem = slugify(property_obj.title)[:140] or "listing"
            candidate = f"{stem}-{property_obj.id}"
            property_obj.share_slug = candidate
            property_obj.save(update_fields=["share_slug"])
        seen.add((property_obj.agency_id, candidate))


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0006_agency_custom_domain_agency_seo_description_and_more"),
        ("properties", "0008_property_seo_description_property_seo_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_share_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                fields=("agency", "share_slug"),
                name="unique_agency_property_share_slug",
            ),
        ),
    ]
