# Generated by Django 5.2.16 on 2026-08-07 05:26

from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


def backfill_land_area_sqft(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    factors = {
        "sqft": Decimal("1"), "sqm": Decimal("10.7639104167"),
        "ropani": Decimal("5476"), "aana": Decimal("342.25"),
        "paisa": Decimal("85.5625"), "daam": Decimal("21.390625"),
        "bigha": Decimal("72900"), "kattha": Decimal("3645"), "dhur": Decimal("182.25"),
    }
    for property_obj in Property.objects.exclude(land_area_value__isnull=True).iterator():
        factor = factors.get(property_obj.land_area_unit)
        if factor:
            property_obj.land_area_sqft = property_obj.land_area_value * factor
            property_obj.save(update_fields=["land_area_sqft"])


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_agency_is_website_published_agency_website_config_and_more"),
        ("properties", "0009_property_custom_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="has_drainage",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="has_electricity",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="has_sewage",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="has_water_supply",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="land_area_sqft",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=4,
                editable=False,
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_use_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("agricultural", "Agricultural"),
                    ("plotting", "Plotting"),
                    ("mixed_use", "Mixed Use"),
                    ("industrial", "Industrial"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="landmark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="major_road_distance_unit",
            field=models.CharField(
                choices=[("m", "Meter"), ("km", "Kilometer")],
                default="m",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="major_road_distance_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="major_road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ring_road", "Ring Road"),
                    ("highway", "Highway"),
                    ("main_road", "Major Road"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="mohada_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="municipality",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="property",
            name="nearest_major_road",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="pichhad_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="plot_dimension_unit",
            field=models.CharField(
                choices=[("ft", "Feet"), ("m", "Meter")], default="ft", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="plot_shape",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rectangular", "Rectangular"),
                    ("square", "Square"),
                    ("regular", "Regular"),
                    ("irregular", "Irregular"),
                    ("triangular", "Triangular"),
                    ("corner", "Corner Plot"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blacktopped", "Blacktopped / Pitched"),
                    ("concrete", "Concrete"),
                    ("gravel", "Gravel"),
                    ("unpaved", "Unpaved"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tole",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="property",
            name="ward_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="property",
            name="built_up_area_unit",
            field=models.CharField(
                choices=[
                    ("aana", "Aana"),
                    ("ropani", "Ropani"),
                    ("paisa", "Paisa"),
                    ("daam", "Daam"),
                    ("kattha", "Kattha"),
                    ("dhur", "Dhur"),
                    ("bigha", "Bigha"),
                    ("sqft", "Square Feet"),
                    ("sqm", "Square Meter"),
                ],
                default="sqft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aana", "Aana"),
                    ("ropani", "Ropani"),
                    ("paisa", "Paisa"),
                    ("daam", "Daam"),
                    ("kattha", "Kattha"),
                    ("dhur", "Dhur"),
                    ("bigha", "Bigha"),
                    ("sqft", "Square Feet"),
                    ("sqm", "Square Meter"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(
                choices=[
                    ("Koshi", "Koshi Province"), ("Madhesh", "Madhesh Province"),
                    ("Bagmati", "Bagmati Province"), ("Gandaki", "Gandaki Province"),
                    ("Lumbini", "Lumbini Province"), ("Karnali", "Karnali Province"),
                    ("Sudurpashchim", "Sudurpashchim Province"),
                ],
                max_length=100,
            ),
        ),
        migrations.RunPython(backfill_land_area_sqft, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["district", "municipality", "ward_number"],
                name="properties__distric_76c74f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["land_use_classification", "property_type"],
                name="properties__land_us_49ed4e_idx",
            ),
        ),
    ]
