# Generated by Django 5.2.16 on 2026-08-07 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_agency_is_website_published_agency_website_config_and_more"),
        ("properties", "0010_property_has_drainage_property_has_electricity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_identity_verified", models.BooleanField(default=False)),
                (
                    "owner_identity_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("ownership_document_received", models.BooleanField(default=False)),
                (
                    "ownership_document_received_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("physically_inspected", models.BooleanField(default=False)),
                (
                    "physically_inspected_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("documents_reviewed", models.BooleanField(default=False)),
                ("documents_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("fully_verified", models.BooleanField(default=False)),
                ("fully_verified_at", models.DateTimeField(blank=True, null=True)),
                ("inspection_notes", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_verifications",
                        to="agencies.agency",
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="properties.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_property_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyVerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lalpurja", "Lalpurja"),
                            (
                                "owner_identity",
                                "Owner citizenship or company registration",
                            ),
                            ("napi_naksa", "Napi Naksa or trace map"),
                            ("char_killa", "Char Killa"),
                            ("malpot_receipt", "Malpot receipt"),
                            ("property_tax_clearance", "Property-tax clearance"),
                            ("building_map_approval", "Building map approval"),
                            (
                                "construction_completion",
                                "Construction-completion certificate",
                            ),
                            ("power_of_attorney", "Power of attorney"),
                            (
                                "marketing_authorization",
                                "Agency marketing authorization",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("received", "Received"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected / Needs Correction"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="missing",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="property_verification/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_verification_documents",
                        to="agencies.agency",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_property_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.propertyverification",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("verification", "document_type"),
                        name="unique_property_verification_document_type",
                    )
                ],
            },
        ),
    ]
