# Generated by Django 5.2.16 on 2026-08-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_agency_is_website_published_agency_website_config_and_more"),
        ("properties", "0011_propertyverification_propertyverificationdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="availability_verified_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="owner_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="republish_approval_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="republish_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="republish_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_property_republishes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="republish_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="republish_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="republish_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_property_republishes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="requires_republish_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="withdrawal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("under_negotiation", "Under Negotiation"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                    ("withdrawn", "Withdrawn"),
                    ("hidden", "Hidden"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PropertyDuplicateFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Needs Review"),
                            ("confirmed", "Confirmed Duplicate"),
                            ("dismissed", "Not a Duplicate"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_duplicate_flags",
                        to="agencies.agency",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates",
                        to="properties.property",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_flags",
                        to="properties.property",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_property_duplicates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "candidate"),
                        name="unique_property_duplicate_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("freshness_confirmed", "Freshness Confirmed"),
                            ("expired", "Listing Expired"),
                            ("republish_requested", "Republish Requested"),
                            ("republish_approved", "Republish Approved"),
                            ("republish_rejected", "Republish Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("duplicate_flagged", "Duplicate Flagged"),
                            ("report_received", "Public Report Received"),
                        ],
                        max_length=40,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_history_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_history",
                        to="agencies.agency",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "created_at"],
                        name="properties__propert_42a2b3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyListingReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_at", models.DateTimeField()),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("seven_days", "7 Days Before Expiry"),
                            ("three_days", "3 Days Before Expiry"),
                            ("one_day", "1 Day Before Expiry"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freshness_reminders",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "expiry_at", "reminder_type"),
                        name="unique_property_expiry_reminder",
                    )
                ],
            },
        ),
    ]
