# Generated by Django 5.2.16 on 2026-08-07 08:44

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_agency_is_website_published_agency_website_config_and_more"),
        ("properties", "0013_backfill_listing_freshness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("view", "Property View"),
                    ("whatsapp_click", "WhatsApp Click"),
                    ("viber_click", "Viber Click"),
                    ("call_click", "Call Click"),
                    ("inquiry", "Inquiry"),
                    ("site_visit_request", "Site Visit Request"),
                    ("distribution_click", "Distribution Link Click"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PropertyDistributionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=properties.models.generate_distribution_code,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("source", models.CharField(max_length=100)),
                ("medium", models.CharField(default="social", max_length=100)),
                ("campaign", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_distribution_links",
                        to="agencies.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_property_distribution_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_links",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agency", "property", "source"],
                        name="properties__agency__078aeb_idx",
                    ),
                    models.Index(
                        fields=["code", "is_active"], name="properties__code_6b9819_idx"
                    ),
                ],
            },
        ),
    ]
