# Generated by Django 5.2.15 on 2026-08-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_propertyevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyhistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('freshness_confirmed', 'Freshness Confirmed'), ('expired', 'Listing Expired'), ('republish_requested', 'Republish Requested'), ('republish_approved', 'Republish Approved'), ('republish_rejected', 'Republish Rejected'), ('withdrawn', 'Withdrawn'), ('duplicate_flagged', 'Duplicate Flagged'), ('report_received', 'Public Report Received'), ('verification_changed', 'Verification Changed'), ('document_changed', 'Verification Document Changed')], max_length=40),
        ),
    ]
