# Generated by Django 5.2.15 on 2026-07-11 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_socialoauthstate_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='social_media.socialaccount'),
        ),
    ]
