# Generated by Django 5.2.15 on 2026-07-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_socialpost_external_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='target_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('partial', 'Partially Published'), ('failed', 'Failed')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='SocialPublishResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=255)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_results', to='social_media.socialpost')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_results', to='social_media.socialaccount')),
            ],
            options={
                'ordering': ['platform', 'id'],
                'constraints': [models.UniqueConstraint(fields=('post', 'social_account'), name='unique_social_publish_target')],
            },
        ),
    ]
