# Generated by Django 5.2.15 on 2026-07-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_socialpost_target_platforms_alter_socialpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_subscription_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
