# Generated by Django 5.2.15 on 2026-06-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='agency',
            name='license_number',
            field=models.CharField(default='TEMP_LICENSE', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
