# Generated by Django 5.2.15 on 2026-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_remove_agency_slug_remove_agency_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
    ]
