# Generated by Django 5.2.15 on 2026-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_paid_at_agency_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='viber_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
