# Generated by Django 5.2.15 on 2026-07-11 01:22

from django.db import migrations, models
from django.utils.text import slugify


def populate_agency_slugs(apps, schema_editor):
    Agency = apps.get_model("agencies", "Agency")

    for agency in Agency.objects.filter(slug__isnull=True).iterator():
        agency.slug = slugify(
            f"{agency.name}-{agency.license_number}"
        )[:180]
        agency.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agency_facebook_url_agency_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='agency_branding/covers/'),
        ),
        migrations.AddField(
            model_name='agency',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency_branding/logos/'),
        ),
        migrations.AddField(
            model_name='agency',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_agency_slugs,
            migrations.RunPython.noop,
        ),
    ]
