# Generated by Django 5.2.16 on 2026-08-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0005_agency_about_agency_address_agency_business_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agency",
            name="seo_description",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="agency",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
