# Generated by Django 5.2.15 on 2026-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_agency_custom_domain_agency_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_website_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='website_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agency',
            name='website_template',
            field=models.CharField(default='luxury-agency', max_length=80),
        ),
    ]
