# Generated by Django 5.2.15 on 2026-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_agency_is_website_published_agency_website_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='default_date_system',
            field=models.CharField(choices=[('ad', 'Anno Domini (AD)'), ('bs', 'Bikram Sambat (BS)')], default='ad', max_length=2),
        ),
        migrations.AddField(
            model_name='agency',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'नेपाली')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='agency',
            name='message_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agency',
            name='municipality',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agency',
            name='timezone',
            field=models.CharField(default='Asia/Kathmandu', max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='tole',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agency',
            name='use_nepali_digits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='ward_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
