# Generated by Django 5.2.16 on 2026-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="password_hash",
            field=models.CharField(default="!", max_length=255),
        ),
        migrations.AddField(
            model_name="invitation",
            name="delivery_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="owner",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
