# Generated by Django 5.2.16 on 2026-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_agentreview_publicsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicsubmission",
            name="kind",
            field=models.CharField(
                choices=[
                    ("contact", "Contact"),
                    ("property_inquiry", "Property inquiry"),
                    ("valuation", "Home valuation"),
                    ("newsletter", "Newsletter"),
                    ("buyer_guide", "Buyer guide"),
                    ("career", "Career"),
                    ("demo", "Product demo"),
                    ("listing_report", "Listing report"),
                ],
                max_length=30,
            ),
        ),
    ]
