# Generated by Django 5.2.16 on 2026-08-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_leadinteraction_direction_alter_lead_source_and_more"),
        ("operations", "0005_alter_publicsubmission_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="leads.lead",
            ),
        ),
    ]
