# Generated by Django 5.2.15 on 2026-08-14 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_document_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="generated_from",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_occurrence",
                to="operations.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Does not repeat"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=30,
            ),
        ),
    ]
