# Generated by Django 5.2.15 on 2026-08-14 07:10

from django.db import migrations, models


def normalize_pipeline_integrity(apps, schema_editor):
    PipelineStage = apps.get_model("operations", "PipelineStage")
    tenant_pipelines = PipelineStage.objects.values_list(
        "agency_id", "module"
    ).distinct()
    for agency_id, module in tenant_pipelines:
        stages = list(PipelineStage.objects.filter(
            agency_id=agency_id, module=module
        ).order_by("sort_order", "id"))
        used = set()
        for stage in stages:
            order = stage.sort_order
            while order in used:
                order += 1
            updates = []
            if order != stage.sort_order:
                stage.sort_order = order
                updates.append("sort_order")
            if stage.is_won and not stage.is_closed:
                stage.is_closed = True
                updates.append("is_closed")
            if updates:
                stage.save(update_fields=updates)
            used.add(order)


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_restore_website_publish_default'),
        ('operations', '0007_task_generated_from_alter_task_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_check_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_match_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(normalize_pipeline_integrity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('agency', 'module', 'sort_order'), name='unique_agency_pipeline_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('is_won', False), ('is_closed', True), _connector='OR'), name='won_pipeline_stage_must_be_closed'),
        ),
    ]
